#!/usr/bin/env bash
# 0-world_wide_web.sh: Audit a domain and its subdomains.

digger () {
    local domain="$1"
    local subdomain="$2"

    get_record() {
        local full_domain="$1.$domain"
        local record_type
        local ip

        record_type=$(dig "$full_domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $(NF - 1)}')
        ip=$(dig "$full_domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $NF}')

        echo "The subdomain $1 is a $record_type record and points to $ip"
    }

    if [ -z "$subdomain" ]; then
        for sub in www lb-01 web-01 web-02; do
            get_record "$sub"
        done
    else
        get_record "$subdomain"
    fi
    return 0
}

if [ $# -lt 1 ]; then
    echo "Usage: ./0-world_wide_web <domain> [<subdomain>]"
else
    digger "$1" "$2"
fi
