#!/usr/bin/env bash
# 0-transfer_file.sh: A script to transfer a file to a Ubuntu server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
HOST_IP=$2
USERNAME=$3
KEY=$4

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE_PATH" "$USERNAME"@"$HOST_IP":~/
