#!/usr/bin/env bash
# 1-install_nginx_web_server: A script to install and configure Nginx to serve "Hello World!" on an Ubuntu server

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the HTML file to be served by Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx service to apply changes
sudo service nginx restart
