#!/usr/bin/env bash
# 3-redirection.sh: A script that redirects /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4

#Install nginx if not already pre-installed
sudo apt-get -y update
sudo apt-get install -y nginx

# Create the HTML file to be served by Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

#Configure /redirect_me
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#Restart nginx
sudo service nginx restart
