#!/usr/bin/env bash
# 0-iamsomeoneelse.sh: Run software as another user.

# Check if an argument is passed
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Store the username from the argument
USER=$1

# Run the whoami command as the specified user
sudo -u "$USER" whoami

